### ISSUE TITLE
Can we get other java clients generated?

### ISSUE THREAD

**Issue by hrstoyanov** [ory/kratos-client-java#2]
@aeneasr
The current generated Java client library seems geared towards Java 7 with a lot of outdated/unnecessary dependency baggage:
```
io.swagger:swagger-annotations com.google.code.findbugs:jsr305 com.squareup.okhttp3:okhttp com.squareup.okhttp3:logging-interceptor com.google.code.gson:gson io.gsonfire:gson-fire org.apache.oltu.oauth2:org.apache.oltu.oauth2.client org.apache.commons:commons-lang3 org.threeten:threetenbp javax.annotation:jsr250-api junit:junit
```

The [OpenAPI code generator](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/java.md) allows for more modern generated code when specifying **library=native** or **library=microprofile** rather than what appears to be currently used **library=okhttp-gson** (e.g. the default option)

Ideally, what would be pushed to maven central are at least 3 artifacts (1 legacy + 2 new), that developers can choose from, for example (in Gradle project):
```
implementation 'sh.ory.kratos:kratos-client:0.5.4-alpha.1' //For current users
implementation 'sh.ory.kratos:kratos-client-native:0.5.4-alpha.1' //For Java 11+ users
implementation 'sh.ory.kratos:kratos-client-microprofile:0.5.4-alpha.1' //For microprofile users
```

This is mostly maven/gradle code generation effort. I can take a stab at it, but need to know if you use maven or gradle for code generation (I see both present?)

**Comment by aeneasr** [comment]
Yes I think library=native should be an option! I think we should keep okhttp-gson around for people using older Java versions. The generation happens here: https://github.com/ory/sdk

We use Maven Central for pushing the artifacts!

**Comment by hrstoyanov** [comment]
Thanks @aeneasr 
As a workaround for me, I added this to my project:

```
project(':ory-kratos-java-mp'){
    apply plugin: 'org.openapi.generator'
    apply plugin: 'java-library'
    apply plugin: 'io.quarkus'
    openApiGenerate {
        generatorName = "java"
        inputSpec = "$projectDir/ory-kratos.yaml".toString()
        outputDir = "$projectDir".toString()
        apiPackage = "ory.kratos.api"
        invokerPackage = "ory.kratos.invoker"
        modelPackage = "ory.kratos.model"
        configOptions = [
                dateLibrary: "java8",
                java8: "true",
                library:"microprofile"
        ]
        globalProperties = [
                modelDocs: "false",
                apiDocs: "false",
                modelDocs:"false",
                apiTests:"false",
                modelTests:"false"
        ]
        skipValidateSpec = true
        logToStderr = true
        generateAliasAsModel = false
    }
    dependencies {
        api enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
        api 'io.quarkus:quarkus-jsonb'
        api 'io.quarkus:quarkus-rest-client'
    }
}
```
and it looks nice, though I still had to file [an issue](https://github.com/OpenAPITools/openapi-generator/issues/8016) with the OpenApi Generator project.

So to generate Java 11+ artifacts, change above to:  ```library:"native"```

I suggest you use the [Gradle OpenAPI plugin](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin) - it can very easily generate all types of Java client and push them to Maven central, all in one neat project! Not sure Maven can do that.

**Comment by aeneasr** [comment]
Thank you for the update and sorry for my late reply! I guess we can switch to the native library at some point. Given that the current set up works (it's just not yet really that great) I think we can push this back a bit as we have so much other stuff going on right now :)

**Comment by hrstoyanov** [comment]
No worries. I  generate my own ORY/Kratos client for a Quarkus app, see no issue creating a native one too. Here is my gradle code in case someone is in the same boat:

```
plugins {
    id 'org.openapi.generator'
    id 'java-library'

    //Needed for CDI bean discovery, see https://quarkus.io/guides/cdi-reference#bean_discovery
    id 'org.kordamp.gradle.jandex'
}

version kratosVersion

openApiGenerate {
    generatorName = "java"
    inputSpec = "$projectDir/ory-kratos.yaml".toString()
    outputDir = "$projectDir".toString()
    apiPackage = "whatever.ory.kratos.api"
    invokerPackage = "whatever.ory.kratos.invoker"
    modelPackage = "whatever.ory.kratos.model"
    configOptions = [
            dateLibrary        : "java8",
            java8              : "true",
            useRuntimeException: "true",
            library            : "microprofile"
//                ,
//                serializationLibrary:"jackson"
    ]
    globalProperties = [
            modelDocs : "false",
            apiDocs   : "false",
            modelDocs : "false",
            apiTests  : "false",
            modelTests: "false"
    ]
    skipValidateSpec = true
    logToStderr = true
    generateAliasAsModel = false
}

dependencies {
    api "io.quarkus:quarkus-jsonb:${quarkusPluginVersion}"
    api "io.quarkus:quarkus-rest-client:${quarkusPluginVersion}"

}
```
A few  remarks:
- I added the ```ory-kratos.yaml``` specification file in the root of my project.
-The generated code is not super clean, you need to scrub imports manually. See [this](https://github.com/OpenAPITools/openapi-generator/issues/8016)
- I check in the generated code in git, this way you re-generate only when you upgrade Kratos.

**Comment by aeneasr** [comment]
I am so done with the Java ecosystem - closing this one because it is already hard enough to publish one Java package 😞
