### ISSUE TITLE
Latest version not in maven centeral

### ISSUE THREAD

**Issue by devnet-io** [ory/kratos-client-java#4]
The version specified in the README, v0.6.0-alpha.2, does not appear to [exist in maven central](https://search.maven.org/artifact/sh.ory.kratos/kratos-client). Would it be possible publish this version? What is currently published does not seem to be compatible with the current version of Kratos.

**Comment by aeneasr** [comment]
Oh maven, how I love you ... unfortunately the release process for Java is really difficult and often flaky with timeouts. Even though maintainers have complained about it for years it is still a well known issue in the ecosystem. Anyways, we'll try to re-release an alpha.3 version soon, maybe the gods will have mercy and not let the publish process time out ;)

**Comment by aeneasr** [comment]
I am giving up. If you have ideas how to fix, for example, https://app.circleci.com/pipelines/github/ory/sdk/314/workflows/2d0ab9f5-4e82-4a75-8b2d-fc138674801c/jobs/294 please let me know
