### ISSUE TITLE
v0.7.1-alpha.1 artifact missing

### ISSUE THREAD

**Issue by jkaa** [ory/kratos-client-java#7]
**Documentation in Repo states to use v0.7.1-alpha.1 but artifact is missing in maven central.**

Latest version available is 0.6.3-alpha.1
https://mvnrepository.com/artifact/sh.ory.kratos/kratos-client

Version 0.6.3-alpha.1 is incompatible with deployed kratos version >= v0.7.1

Any news on when the artifact will be published?

**Comment by jkaa** [comment]
Any news on that?

**Comment by aeneasr** [comment]
Sorry, I didn't have time to look into this yet. I don't know why Java artifact uploads are failing as of recently...

**Comment by zhming0** [comment]
I think the generated code doesn't compile. I tried it in local but it failed with a bunch of compilation error. 
`v0.6.3-alpha.1` compiles though.

**Comment by aeneasr** [comment]
Looks like there's another issue with the release script: https://app.circleci.com/pipelines/github/ory/sdk/480/workflows/29211c8a-908c-4aa7-8b01-073509692989/jobs/462?invite=true#step-105-2131

**Comment by aeneasr** [comment]
Resolved that, now it's failing with: https://app.circleci.com/pipelines/github/ory/sdk/492/workflows/8466ae86-529f-4297-a9fe-631111a55206/jobs/473

**Comment by aeneasr** [comment]
Yay, looks like a Maven bug - who doesn't love the Java Maven ecosystem 😓 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980467

**Comment by aeneasr** [comment]
Finally the f*cking toolchain is working again, but we end up with a compile error: https://app.circleci.com/pipelines/github/ory/sdk/509/workflows/1af3d872-efb5-48bb-ada6-a8dca9ccdf79/jobs/483

Giving up for now, if you have ideas how to resolve it be my guest :)

**Comment by aeneasr** [comment]
This has been resolved now! It was a mixture of various things. We have not released it yet, but the next release will pass! 🎉
